# The format of the sound name is the same as the "/playsound" command in Minecraft.
default:
  message:
    sound: "block.note.bass"
    volume: 1
    pitch: 2
    # Default message sending speed.
    speed: 1
  selection:
    move:
      sound: "block.note.hat"
      volume: 1
      pitch: 1
    select:
      sound: "entity.arrow.hit_player"
      volume: 1
      pitch: 1
  # This is the setting to stop the player while sending a message.
  freeze:
    horizontal-freeze: true
    verticalf-freeze: false
    freeze-player-invincible: true
    leftclick-cancel: true
    rightclick-cancel: true
# The type of click used to progress through the message. Choose from the following three types.
# right, left, all
  click-type: "all"
