# The format of the sound name is the same as the "/playsound" command in Minecraft.
default:
  message:
    sound: "block.note.bass"
    volume: 1
    pitch: 2
    # Number of characters displayed per second
    speed: 20
    # The default color of the text. This string will be placed at the beginning of the sentence.
    color: "§r"

  selection:
    move:
      sound: "block.note.hat"
      volume: 1
      pitch: 1
    select:
      sound: "entity.arrow.hit_player"
      volume: 1
      pitch: 1

  # Stop the player while sending a message.
  freeze:
    horizontal-freeze: true
    verticalf-freeze: false
    freeze-player-invincible: true
    leftclick-cancel: true
    rightclick-cancel: true
