name: RPGText
version: 1.1
main: seisyun.rpgtext.RPGText

commands:
  rpgtext:
    permission: rpgtext
    discription: send text messages with a slight delay and sound using the player's actionbar
    using: /rpgtext <player> <text|config> <text>